name: Issue
description: Report an issue with the mod
labels: ["bug"]
type: "Bug"
title: "[BUG] "
body:
  - type: markdown
    attributes:
      value: "**Welcome to submit a new issue!**\n- It takes only 3 steps, so please be patient :)\n- Tip: If your issue is not a feature request and is not an issue (e.g. \"how do I use X feature\"), please use [Discussions](https://github.com/redstone-llc/HTSLReborn/discussions) instead."

  - type: checkboxes
    attributes:
      label: "Step 1. Before you submit"
      description: "Hint: The 2nd checkbox is **not** required as you may have failed to do so."
      options:
        - label: I have read the above instructions and am sure that this is supposed to be posted here.
          required: true
        - label: I've successfully updated to the latest version.
          required: false
        - label: I've ticked the checkboxes without reading their contents
          required: false

  - type: textarea
    attributes:
      label: "Step 2. Version info"
      description: "What version of the mod are you having trouble with? Minecraft version?"
    validations:
      required: true

  - type: textarea
    attributes:
      label: "Step 3. Describe the issue"
      description: "Include clear steps to reproduce the issue."
    validations:
      required: true