name: Feature request
description: Suggest a new feature
labels: ["enhancement"]
type: "Feature"
title: "[FEATURE] "
body:
  - type: markdown
    attributes:
      value: "**Welcome to submit a new feature request!**"

  - type: textarea
    attributes:
      label: "What would you like to be added?"
      description: "Can be a suggestion for enhancing an existing feature, too."

  - type: textarea
    attributes:
      label: "How will it help?"
      description: "It's helpful to include examples (like in your use case). How will this improve the mod?"

  - type: textarea
    attributes:
      label: "Extra info"
      description: "Anything else you'd like to add."
