name: Feature request
description: Suggest a new feature.
labels: ["triage"]
type: "Feature"
body:
  - type: markdown
    attributes:
      value: |
        **Thanks for caring about improving HTSL Reborn!**
        Feel free to suggest any additions or improvements to the mod that you'd like to see implemented in the future.

  - type: textarea
    attributes:
      label: "What would you like to be added?"
      description: "Can be a suggestion for enhancing an existing feature, too."

  - type: textarea
    attributes:
      label: "How will it help?"
      description: "It's helpful to include examples (like in your use case). How will this improve the mod?"
